def gv
pipeline {
  agent any
  tools{
    maven "maven-3.9"
  }
  stages {
    stage("init") {
      steps {
        script {
          gv = load "java-maven-app/script.groovy"
        }
      }
    }
    stage('increment version'){
      steps{
        script{
          echo 'increment app version...'
          sh 'mvn -f java-maven-app/pom.xml build-helper:parse-version versions:set -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} versions:commit'
          def matcher = readFile('java-maven-app/pom.xml') =~ '<version>(.+)</version>'
          def version = matcher[0][1]
          env.IMAGE_NAME = "$version-$BUILD_NUMBER"
        }
      }
    }
     stage("build Jar") {
      steps {
        script {
          gv.buildJar()
        }
      }
    }
    stage("build Image") {
      steps {
        script {
          gv.buildImage()
        }
      }
    }
    stage("deploy") {
      steps { 
        script {
          gv.deployApp()   
        }
      }
    }
  }
}
