def gv
pipeline {
  agent any
  tools{
    maven "maven-3.9"
  }
  stages {
    stage("init") {
      steps {
        script {
          gv = load "java-maven-app/script.groovy"
        }
      }
    }
     stage("build Jar") {
      steps {
        script {
          gv.buildJar()
        }
      }
    }
    stage("build Image") {
      steps {
        script {
          gv.buildImage()
        }
      }
    }
    stage("deploy") {
      steps { 
        script {
          echo 'deploying app ...'
          gv.deployApp()   
        }
      }
    }
  }
}
